--Создание таблицы "Users"
CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL
);

--Добавление записи в таблицу "Users"
INSERT INTO "Users" ("first_name", "last_name") VALUES ('Имя', 'Фамилия');

--Чтение всех записей из таблицы "Users"
SELECT * FROM "Users";

--Изменение записи в таблице "Users" (по ID)
UPDATE "Users" SET "first_name" = 'Новое Имя', "last_name" = 'Новая фамилия' WHERE "id" = 1;

--Удаление записи из таблицы "Users" (по ID)
DELETE FROM "Users" WHERE "id" = 1;

--Создание таблицы "Cards"
CREATE TABLE "Cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" varchar UNIQUE NOT NULL,
  "balance" decimal NOT NULL,
  "limit" decimal NOT NULL,
  "info" varchar,
  "user_id" integer NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "Users" ("id")
);

--Добавление записи в таблицу "Cards"
INSERT INTO "Cards" ("number", "balance", "limit", "info", "user_id") VALUES ('111111111', -1000.00, -5000.00, '', 1);

--Чтение всех записей из таблицы "Cards"
SELECT * FROM "Cards";

--Изменение записи в таблице "Cards" (по ID)
UPDATE "Cards" SET "number" = '888888888', "balance" = -1500.00, "limit" = -6000.00, "user_id" = 2 WHERE "id" = 1;

--Удаление записи из таблицы "Cards" (по ID)
DELETE FROM "Cards" WHERE "id" = 1;
