CREATE TABLE "Users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL
);

CREATE TABLE "Cards" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "number" varchar UNIQUE NOT NULL,
  "balance" decimal NOT NULL,
  "limit" decimal NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE "Labels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "color" varchar NOT NULL,
  "description" text,
  "user_id" integer
);

CREATE TABLE "Transactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card_id" integer NOT NULL,
  "amount" decimal NOT NULL,
  "datetime_utc" timestamp NOT NULL,
  "type" varchar NOT NULL
);

CREATE TABLE "TransactionsLabels" (
  "transaction_id" integer NOT NULL,
  "label_id" integer NOT NULL
);

ALTER TABLE "Cards" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Labels" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Transactions" ADD FOREIGN KEY ("card_id") REFERENCES "Cards" ("id");

ALTER TABLE "TransactionsLabels" ADD FOREIGN KEY ("transaction_id") REFERENCES "Transactions" ("id");

ALTER TABLE "TransactionsLabels" ADD FOREIGN KEY ("label_id") REFERENCES "Labels" ("id");
