apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaroshenko-auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service-app
  template:
    metadata:
      name: auth-service-pod
      labels:
        app: auth-service-app
    spec:
      containers:
        - name: auth-service-container
          image: registry.gitlab.com/shift-python/y2023/homeworks/yaroshenko-as/week8/auth-service-app:latest
          ports:
            - containerPort: 24028
          env:
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  key: app_host
                  name: iaroshenko-config
            - name: KAFKA_HOST
              valueFrom:
                configMapKeyRef:
                  key: kafka_host
                  name: iaroshenko-config
            - name: KAFKA_PORT
              valueFrom:
                configMapKeyRef:
                  key: kafka_port
                  name: iaroshenko-config
            - name: APP_AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  key: app_auth_port
                  name: iaroshenko-config
            - name: REAL_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: real_database_url
                  name: iaroshenko-config
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db_username
                  name: iaroshenko-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: iaroshenko-secret
          livenessProbe:
            tcpSocket:
              port: 24028
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 24028
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 800Mi
