--Создание таблицы "Admin"
CREATE TABLE "Admin" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar NOT NULL,
  "password" varchar NOT NULL,
);

--Добавление записи в таблицу "Admin"
INSERT INTO "Admin" ("username", "password") VALUES ('bob', '123');

--Чтение всех записей из таблицы "Admin"
SELECT * FROM "Admin";

--Изменение записи в таблице "Admin" (по ID)
UPDATE "Admin" SET "username" = 'Alex', "password" = '777' WHERE "id" = 1;

--Удаление записи из таблицы "Admin" (по ID)
DELETE FROM "Admin" WHERE "id" = 1;
